name: upload invites draw
on:
  workflow_dispatch:
  push: []
  schedule:
    - cron: '0 8 * * *'
jobs:
  Update-Express-Entry-Draws:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.x'
      - name: Install SSH Key
        uses: LuisEnMarroquin/setup-ssh-action@v2.0.0
        with:
          SSHKEY: ${{ secrets.SSH_KEY }}
          ORIGIN: python3.ninja
          USER: zodman
      - run: ssh  zodman@python3.ninja ls --help
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.in
      - run: bake ee
      - run: bake deploy
